services:
  redis:
    image: redis:7.2-alpine
    container_name: redis
    ports:
      - "6379:6379"

  worker:
    image: vllm/vllm-openai:latest
    container_name: llm-worker
    environment:
      - REDIS_BROKER_URL=redis://redis:6379/0
      - PYTHONPATH=/workspace
    volumes:
      - ./:/workspace:rw
      - ./data:/workspace/data:rw
      - ./huggingface_cache:/root/.cache/huggingface
    working_dir: /workspace
    entrypoint: ["/bin/bash", "-c", "pip install celery redis rq fastapi uvicorn && celery -A llm_worker_start.app worker --loglevel=info"]
    command: []
    depends_on:
      - redis
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
